# Copyright 2018 Vinnie Falco
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

sudo: true
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
script:
  - mkdir build
  # - cd build
  # - cmake ..
  # - make
after_success:
  - wget -qO- https://cli-assets.heroku.com/install.sh | sh
  - docker login -e _ -u _ --password=$HEROKU_API_KEY registry.heroku.com
  - heroku container:push web --app $HEROKU_APP_NAME --password=$HEROKU_API_KEY
  - heroku container:release web --app $HEROKU_APP_NAME --password=$HEROKU_API_KEY
  
notifications:
  email:
    on_failure: never
    on_success: never
