# Copyright 2018 Vinnie Falco
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

sudo: true
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
script:
  - wget http://downloads.sourceforge.net/project/boost/boost/1.68.0/boost_1_68_0.tar.gz
  - tar xfz boost_1_68_0.tar.gz
  - rm boost_1_68_0.tar.gz
  - cd boost_1_68_0
  - ./bootstrap.sh --with-libraries=system > /dev/null 2>&1
  - ./b2 install > /dev/null 2>&1
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
after_success:
  - heroku container:login
  - heroku container:push web -a $HEROKU_APP_NAME
  - heroku container:release web -a $HEROKU_APP_NAME
  
notifications:
  email:
    on_failure: never
    on_success: never
